package main

const PHASE_ENVIRONMENT_VARIABLE = "TEST_FRAMEWORK_PHASE"
const ID_ENVIRONMENT_VARIABLE = "TEST_FRAMEWORK_ID"

const DISCOVERY_PHASE_ENVIRONMENT_VAIRABLE = PHASE_ENVIRONMENT_VARIABLE + "=DISCOVERY"
const TEST_PHASE_ENVIRONMENT_VAIRABLE = PHASE_ENVIRONMENT_VARIABLE + "=TEST_RUN"
